

def mental_training():
    import pyautogui
    import time
    import random

    data_first = [2.0, 2.2, 1.9, 2.1, 1.7, 1.8]
    data_second = [1.0, 1.2, 1.5, 1.1, 1.3, 1.4]
    data_wait = [30, 35, 20, 25]
    while True:

        time.sleep(6)
        pyautogui.press('1')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('q')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('4')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('4')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('4')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('4')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('4')
        time.sleep(random.uniform(1.7, 2.2))
        pyautogui.press('q')
        time.sleep(random.uniform(1.0, 1.5))
        pyautogui.press('0')
        time.sleep(random.uniform(24.0, 35.5))

